project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Loris Lombardi"
  site-url: https://lorislombardi.jp

format:
  html:
    minimal: true
    css: style.css
    lang: en
    include-before-body: nav.html
    include-after-body: footer.html
