project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Loris Lombardi"
  site-url: https://lorislombardi.jp
  search:
    location: sidebar
    type: textbox
  sidebar:
    style: floating
    search: true
    header: _sidebar-header.md
    footer: _sidebar-footer.md
    contents:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - text: "---"
      - href: mailto:loris.lombardi.jp@gmail.com
        text: Email
        icon: envelope
      - href: https://orcid.org/0009-0002-4915-1750
        text: ORCID
        icon: person-badge
      - href: https://github.com/lolonifuji
        text: GitHub
        icon: github
      - href: https://www.linkedin.com/in/lorislombardi
        text: LinkedIn
        icon: linkedin
  page-footer:
    center: "© 2026 Loris Lombardi · lorislombardi.jp"

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: style.css
    toc: false
    grid:
      sidebar-width: 270px
      body-width: 980px
      margin-width: 0px
      gutter-width: 3rem
    lang: en
